export const quotes = [
  {
    text: "Connect. Connect",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: true,
  },
  {
    text: "If not we are gonna have to bounce brother",
    author: "Nate Belmar",
    bg: "bg-quote-nate",
    real: true,
  },
  {
    text: "What color is your Bugatti?",
    author: "Andrew Tate",
    bg: "bg-quote-andrew",
    real: true,
  },
  {
    text: "Steve",
    author: "Andrew Tate",
    bg: "bg-quote-andrew",
    real: true,
  },
  {
    text: "Everybody worships but nobody worships the hard work",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: true,
  },
  {
    text: "Guys, this is the video game, we are in it",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: true,
  },
  {
    text: "If you guys work for me, six pack or your fired",
    author: "Andy Elliott",
    bg: "bg-quote-andy",
    real: true,
  },
  {
    text: "I meditate with my Bugatti engine running. Vibration matters.",
    author: "Andrew Tate",
    bg: "bg-quote-andrew",
    real: false,
  },
  {
    text: "Crypto isn’t just currency, it’s consciousness.",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: false,
  },
  {
    text: "If you eat before 5am, you're already behind, brother.",
    author: "Nate Belmar",
    bg: "bg-quote-nate",
    real: false,
  },
  {
    text: "Success is 99% hydration and 1% screaming at your team.",
    author: "Andy Elliott",
    bg: "bg-quote-andy",
    real: false,
  },
  {
    text: "I only sleep standing up. Horizontal is for the weak.",
    author: "Andrew Tate",
    bg: "bg-quote-andrew",
    real: false,
  },
  {
    text: "Wake up. Hustle. Teleport. Repeat.",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: false,
  },
  {
    text: "I don't breathe air, I breathe progress.",
    author: "Nate Belmar",
    bg: "bg-quote-nate",
    real: false,
  },
  {
    text: "Reflect comes from the reflection of the mirror.",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: true,
  },
  {
    text: "You only need a drivers license for commerical driving.",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: true,
  },
  {
    text: "I have a lot of beef with anime",
    author: "Nate Belmar",
    bg: "bg-quote-nate",
    real: true,
  },
  {
    text: "I only drink water sourced from glaciers. Anything else is suboptimal.",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: false,
  },
  {
    text: "If your car doesn’t have wings, you’re not thinking big enough.",
    author: "Andrew Tate",
    bg: "bg-quote-andrew",
    real: false,
  },
  {
    text: "I train my team by making them run marathons in VR.",
    author: "Andy Elliott",
    bg: "bg-quote-andy",
    real: false,
  },
  {
    text: "The stock market is just a multiplayer game of Monopoly.",
    author: "Luke Belmar",
    bg: "bg-quote-luke",
    real: false,
  },
]
